version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    env_file:
      - ./.env
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    restart: unless-stopped
