version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    env_file:
      - ./.env
    ports:
      - '443:443'
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wp_volume:/var/www

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp_volume:/var/www

volumes:
  mariadb_volume:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

  wp_volume:
    driver_opts:
      type: none  # Type none defines a volume that is not managed by Docker
      o: bind     # Bind mounts a file or directory from the host into the container
      device: ${HOME}/data/wordpress

networks:
  inception:
    name: inception_network
    # Bridge driver allows containers to communicate with each other
    driver: bridge
